apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "card-separator.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "card-separator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      {{- include "card-separator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
        {{- include "card-separator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "card-separator.serviceAccountName" . }}
      containers:
      - name: frontend
        image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 5173
          protocol: TCP
        env:
        - name: VITE_API_URL
          value: {{ .Values.frontend.env.VITE_API_URL | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
